---
title: "Development actions history"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r description}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "Graphs of Australian temperatures in summer and winter",
    Version = "0.1",
    Description = "This package contains functions to download data for Australian weather stations and to graph their maximum and minimum daily temperatures in summer and winter.",
    `Authors@R` = c(person(
      "A", "Russo", email = "a.s.russo@outlook.com", role = c("aut", "cre")
    ))
  ),
  overwrite = TRUE
)
# Define License with use_*_license()
usethis::use_gpl_license()
```

# Include datasets

```{r}
local({
  knitr::knit("vignettes/dev_save_data.Rmd", output = tempfile())
  usethis::use_data(Adelaide, overwrite = TRUE)
  usethis::use_data(Brisbane, overwrite = TRUE)
  usethis::use_data(Canberra, overwrite = TRUE)
  usethis::use_data(Darwin, overwrite = TRUE)
  usethis::use_data(Hobart, overwrite = TRUE)
  usethis::use_data(Melbourne, overwrite = TRUE)
  usethis::use_data(Perth, overwrite = TRUE)
  usethis::use_data(Sydney, overwrite = TRUE)
})
```

```{r}
fusen::inflate(flat_file = "dev/data_doc.Rmd",
               vignette_name = NA,
               overwrite = TRUE)
```

# Set extra sources of documentation

```{r, eval=FALSE}
# Install a first time
remotes::install_local()
# README
usethis::use_readme_rmd()
```

# Inflate flat file

```{r development-inflate, eval=FALSE}
fusen::inflate(
  flat_file = "dev/flat_minimal_package.Rmd",
  vignette_name = "dev_save_data",
  overwrite = TRUE,
  open_vignette = FALSE
)
```