# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

library(testthat)

test_that("Incorrect data", {
  expect_error(check_temperatures(mtcars))
})

test_that("Empty object", {
  expect_error(check_temperatures(NULL))
})

test_that("Incorrect object class", {
  expect_error(check_temperatures(1:10))
})

test_that("Missing variables", {
  expect_error(check_temperatures(data.frame(
    Year = numeric(0),
    Month = numeric(0),
    Day = numeric(0)
  )))
})

test_that("Duplicated variables", {
  data <- data.frame(
    Year = numeric(0),
    Month = numeric(0),
    Day = numeric(0),
    Location = character(0),
    Type = character(0),
    Temperature = character(0),
    Temperature2 = character(0) # Variable to duplicate
  )
  colnames(data) <-
    c('Year',
      'Month',
      'Day',
      'Location',
      'Type',
      'Temperature',
      'Temperature')
  expect_error(check_temperatures(data))
})

test_that("Incorrect variable types", {
  expect_error(check_temperatures(
    data.frame(
      Year = numeric(0),
      Month = numeric(0),
      Day = numeric(0),
      Location = character(0),
      Type = character(0),
      Temperature = character(0) # Should be numeric
    )
  ))
})
