# WARNING - Generated by {fusen} from dev/flat_minimal_package.Rmd: do not edit by hand

#' @title
#' Download and clean Australian temperature data
#' 
#' @description
#' `download_temperatures()` downloads maximum and/or minimum daily temperatures
#' for Australian weather stations, cleans and reformats the data, and returns
#' the combined data.
#'
#' @details
#' Daily maximum and/or minimum data for all years for multiple Australian
#' weather stations can be downloaded from the
#' \href{http://www.bom.gov.au/climate/data/}{Climate Data Online section} of
#' the Australian Bureau of Meteorology website.
#' 
#' Any download links must resemble one of the default ones provided below:
#' * \href{http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=122&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023000}{Adelaide (West Terrace / Ngayirdapira) daily maximum temperature}
#' * \href{http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=123&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023000}{Adelaide (West Terrace / Ngayirdapira) daily minimum temperature}
#' * \href{http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=122&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023034}{Adelaide Airport daily maximum temperature}
#' * \href{http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=123&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023034}{Adelaide Airport daily minimum temperature}
#' 
#' The hyperlinks are the same except for the parts containing the:
#' * \strong{product code:} 122 = maximum; 123 = minimum
#' * \strong{station number:} a six-digit code
#' 
#' See the examples section for the valid URL format.
#' 
#' The data returned by `download_temperatures()` can then be graphed using
#' \code{\link{plot_temperatures}}. Locations can be extracted using
#' \code{\link{get_locations}}.
#' 
#' @param URLs A character vector of one or more specified download links.
#' Default links are for Adelaide temperature data (see the details section)
#' 
#' @importFrom dplyr arrange bind_rows contains first last matches mutate n rename select slice
#' @importFrom httr GET http_error user_agent
#' @importFrom padr pad
#' @importFrom readr read_csv read_lines
#' @importFrom rlang .data :=
#' @importFrom rvest html_attr html_element read_html
#' @importFrom stringr str_detect str_extract str_replace str_to_title
#' @importFrom utils download.file unzip
#' 
#' @return The cleaned and combined temperature data
#' 
#' @seealso
#' \code{\link{plot_temperatures}}, \code{\link{get_locations}}
#' 
#' @examples
#' \dontrun{
#' # Download Sydney data instead of default (Adelaide) data
#' # Station: Sydney Airport AMO (number 066037)
#' # Product: Daily maximum temperature
#' URLpart1 <- "http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode="
#' product <- "122"
#' URLpart2 <- "&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num="
#' station <- "066037"
#' download_temperatures(URLs = paste0(URLpart1, product, URLpart2, station))
#' }
#'
#' @export
download_temperatures <-
  function(URLs = c(
    "http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=122&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023000",
    "http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=123&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023000",
    "http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=122&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023034",
    "http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=123&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=023034"
  )) {
    # Define user-agent and headers
    user_agent <-
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
    headers = c(`user-agent` = user_agent)
    
    # Validate URLs argument
    stopifnot("No URL(s) were provided" = !is.null(URLs))
    stopifnot("The URL(s) must be expressed as character strings" = is.character(URLs) == TRUE)
    stopifnot("The URL(s) are not valid" = all(unlist(
      lapply(
        URLs,
        str_detect,
        "^\\Qhttp://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=\\E\\d{3}\\Q&p_display_type=dailyDataFile&p_startYear=&p_c=&p_stn_num=\\E\\d{6}$"
      )
    )) == TRUE)
    stopifnot("The URL(s) returned an error" = !all(unlist(lapply(
      URLs, http_error, user_agent(user_agent)
    ))) == TRUE)
    
    # Initialise raw datasets list
    raw_datasets <- list()
    
    # Extract downloaded datasets
    for (URL in URLs) {
      # Extract download link
      download_link <- GET(URL, user_agent(user_agent)) |>
        read_html() |>
        html_element("#content-block > ul.downloads > li:nth-child(2) > a") |>
        html_attr('href') |>
        paste0('http://www.bom.gov.au', . = _)
      
      # Create temporary file to download zipped file in to
      temp_file <- tempfile(fileext = ".zip")
      
      # Create temporary directory to store zipped file in
      temp_dir <- tempfile()
      
      # Download zipped file
      download.file(
        download_link,
        temp_file,
        mode = "wb",
        headers = headers,
        quiet = TRUE
      )
      
      # Unzip downloaded file
      unzip(zipfile = temp_file, exdir = temp_dir)
      
      # Extract filenames
      data_file <- list.files(temp_dir, '*.csv')
      note_file <- list.files(temp_dir, '*.txt')
      
      # Extract dataset notes
      notes <-
        read_lines(paste(temp_dir, note_file, sep = '/'), skip_empty_rows = TRUE)
      
      # Extract location
      relevant_row_number <- grep('^Station name:', notes)
      relevant_row <- notes[relevant_row_number]
      location <-
        str_to_title(str_replace(relevant_row, 'Station name: ', ''))
      
      # Extract temperature type
      relevant_row_number <- grep('^Notes for Daily', notes)
      relevant_row <- notes[relevant_row_number]
      type <-
        str_extract(str_to_title(relevant_row), pattern = str_to_title(c("maximum|minimum")))
      
      # Extract raw dataset
      raw_dataset <-
        read_csv(
          file.path(temp_dir, data_file),
          col_select = c(.data$Year, .data$Month, .data$Day, contains('degree')),
          show_col_types = FALSE
        ) |>
        mutate(
          Month = as.numeric(.data$Month),
          Day = as.numeric(.data$Day),
          Location = location,
          Type = type
        ) |>
        rename("Temperature" := matches('(degree)'))
      
      # Insert rows for any missing dates
      raw_dataset <- raw_dataset |>
        mutate(Date = as.Date(paste(
          .data$Year, .data$Month, .data$Day, sep = '-'
        ))) |>
        pad(interval = 'day') |>
        select(
          .data$Year,
          .data$Month,
          .data$Day,
          .data$Location,
          .data$Type,
          .data$Temperature,
          -.data$Date
        )
      
      # Remove any starting or ending rows where all measurements are missing
      raw_dataset <- raw_dataset |>
        slice(first(which(!is.na(
          .data$Temperature
        ))):n()) |>
        slice(1:last(which(!is.na(
          .data$Temperature
        ))))
      
      # Merge datasets
      raw_datasets <- append(raw_datasets, list(raw_dataset))
    }
    
    # Combine datasets
    combined_dataset <- bind_rows(raw_datasets) |>
      arrange(.data$Year, .data$Month, .data$Day)
    
    # Return combined datasets
    return(combined_dataset)
}

#' @title
#' Check if Australian temperature data are in the expected format
#' 
#' @description
#' `check_temperatures()` checks if an object conforms to the format as per the dataset
#' returned from \code{\link{download_temperatures}} containing temperatures for
#' Australian weather stations.
#' 
#' @details
#' An error is thrown if the object does not conform to the required format.
#' Otherwise the function returns nothing. Only limited error checking is
#' undertaken, such as checking for appropriate variable names and types.
#' Logical checks for aspects such as consistency within the dataset are not
#' performed.
#' 
#' @param data The object to be checked
#' 
#' @importFrom dplyr pull
#' @importFrom rlang .data
#' 
#' @seealso
#' \code{\link{download_temperatures}}, \code{\link{plot_temperatures}}
#' 
#' @examples
#' \dontrun{
#' # Download Adelaide temperature data (the default)
#' adelaide_data <- download_temperatures()
#'
#' # Check the data for validity (nothing happens if valid)
#' check_temperatures(adelaide_data)
#' }
#'
#' @export
check_temperatures <- function(data) {
  # Check object
  stopifnot("No data object was provided" = !is.null(data))
  stopifnot("Data object not of the expected class" = is.data.frame(data) == TRUE)
  
  # Check variables
  error_flag <- FALSE
  if (any(duplicated(colnames(data))))
    error_flag <- TRUE
  if (!("Year" %in% colnames(data)) |
      is.numeric(pull(data, .data$Year)) == FALSE)
    error_flag <- TRUE
  if (!("Month" %in% colnames(data)) |
      is.numeric(pull(data, .data$Month)) == FALSE)
    error_flag <- TRUE
  if (!("Day" %in% colnames(data)) |
      is.numeric(pull(data, .data$Day)) == FALSE)
    error_flag <- TRUE
  if (!("Location" %in% colnames(data)) |
      is.character(pull(data, .data$Location)) == FALSE)
    error_flag <- TRUE
  if (!("Type" %in% colnames(data)) |
      is.character(pull(data, .data$Type)) == FALSE)
    error_flag <- TRUE
  if (!("Temperature" %in% colnames(data)) |
      is.numeric(pull(data, .data$Temperature)) == FALSE)
    error_flag <- TRUE
  stopifnot("Not all required variables exist, are unique, and/or are in the right format" = error_flag == FALSE)
}

#' @title
#' Get all locations from Australian temperature data
#' 
#' @description
#' `get_locations()` returns all unique locations (weather stations) in the
#' temperature dataset returned by \code{\link{download_temperatures}}.
#' 
#' @param data The tibble returned from \code{\link{download_temperatures}}
#' containing temperature data
#' 
#' @return Sorted, unique locations from the temperature dataset
#' 
#' @seealso
#' \code{\link{download_temperatures}}, \code{\link{check_temperatures}}
#' 
#' @examples
#' \dontrun{
#' # Download Adelaide temperature data (the default)
#' adelaide_data <- download_temperatures()
#'
#' # Extract locations
#' get_locations(adelaide_data)
#' }
#'
#' @export
get_locations <- function(data) {
  # Validate data argument
  check_temperatures(data)
  
  # Return locations
  return(sort(unique(pull(
    data, .data$Location
  ))))
}

#' @title
#' Graph Australian temperature data
#' 
#' @description
#' `plot_temperatures()` graphs maximum or minimum daily temperatures
#' for Australian weather stations.
#'
#' @details
#' Graphs for summer (maximum temperatures) or winter (minimum temperatures) can
#' be produced for a single weather station using the dataset returned from
#' \code{\link{download_temperatures}}.
#' 
#' If the starting and ending years provided are beyond the range of data, then
#' the earliest and latest available years will be used, respectively.
#' 
#' If at least one leap-year is present in the data, then February 29 will
#' appear in the graph for all years, otherwise it will not appear for any year.
#' 
#' Since the summer months used in the graphs (Nov thru Mar) span at least two
#' years, plotting one summer season will comprise at least two rows in the
#' resulting graph (unless the current year is chosen but it is not yet
#' complete).
#' 
#' @param data  The tibble returned from \code{\link{download_temperatures}}
#' containing temperature data
#' @param season One of `summer` or `winter`
#' @param start_year The starting year for the range of data to graph. Default
#' is 31 years ago from the current year
#' @param end_year The ending year for the range of data to graph. Default is
#' the current year
#' @param location The weather station in `data` to graph temperatures for.
#' If `NULL` provided (the default value), then the last location from
#' `get_locations(data)` is used
#' @param thresholds Three ascending numeric thresholds that define the
#' extreme temperatures to graph
#' 
#' @importFrom dplyr arrange bind_rows filter group_by if_else left_join mutate
#' pull row_number select summarise ungroup
#' @importFrom ggplot2 aes element_blank element_rect element_text expansion
#' geom_text geom_tile geom_vline ggplot labs scale_fill_manual
#' scale_x_continuous scale_y_continuous theme
#' @importFrom lubridate leap_year today year
#' @importFrom rlang .data
#' @importFrom stats na.omit
#' @importFrom stringr str_c str_sub str_to_lower str_to_title
#' @importFrom tidyr replace_na
#' @importFrom zoo rollapply
#' 
#' @return A temperature graph
#' 
#' @seealso
#' \code{\link{download_temperatures}}, \code{\link{check_temperatures}},
#' \code{\link{get_locations}}
#' 
#' @examples
#' \dontrun{
#' # Download Adelaide temperature data (the default)
#' adelaide_data <- download_temperatures()
#'
#' # Graph daily maximum temperatures
#' plot_temperatures(data = adelaide_data,
#'                   season = "summer",
#'                   thresholds = c(30, 35, 40))
#' }
#'
#' @export
# Define function to generate temperature graph
plot_temperatures <- function(data,
                              season,
                              start_year = year(today()) - 31,
                              end_year = year(today()),
                              location = NULL,
                              thresholds) {
  # Validate data argument
  check_temperatures(data)
  
  # Validate season argument
  stopifnot("The season must be one of 'summer' or 'winter'" = !is.null(season))
  stopifnot("The season must be one of 'summer' or 'winter'" = str_to_lower(season) %in% c('summer', 'winter'))
  
  # Validate starting and ending year arguments
  stopifnot('The starting year must be an integer' = !is.null(start_year))
  stopifnot('The starting year must be an integer' = is.numeric(start_year))
  stopifnot('The starting year must be an integer' = start_year %% 1 == 0)
  stopifnot('The ending year must be an integer' = !is.null(end_year))
  stopifnot('The ending year must be an integer' = is.numeric(end_year))
  stopifnot('The ending year must be an integer' = end_year %% 1 == 0)
  stopifnot('The starting year must not be greater than the ending year' = start_year <= end_year)
  
  # Validate thresholds argument
  stopifnot('Three ascending numeric thresholds must be provided' = !is.null(thresholds))
  stopifnot('Three ascending numeric thresholds must be provided' = is.numeric(thresholds))
  stopifnot('Three ascending numeric thresholds must be provided' = length(thresholds) == 3)
  stopifnot('Three ascending numeric thresholds must be provided' = thresholds[1] < thresholds[2])
  stopifnot('Three ascending numeric thresholds must be provided' = thresholds[2] < thresholds[3])
  
  # Validate location argument
  if (is.null(location)) {
    location <- last(get_locations(data))
  }
  locations <- get_locations(data)
  stopifnot('The location is not available' = str_to_lower(location) %in% str_to_lower(locations))
  
  # Argument modifications
  season <- str_to_lower(season)
  location <- str_to_title(location)
  
  # Extract relevant months
  relevant_data <- data |>
    filter(
      if (season == 'summer') {
        (.data$Month < 4 | .data$Month > 10)
      } else {
        (.data$Month >= 5 & .data$Month <= 9)
      },
      .data$Type == ifelse(season == 'summer', 'Maximum', 'Minimum'),
      .data$Location == location
    )
  
  # Abort if dataset is empty
  stopifnot('There are no data to plot' = nrow(relevant_data) > 0)
  
  # Adjust start year
  min_start_year <- relevant_data |>
    pull(.data$Year) |>
    min()
  start_year <-
    max(start_year, min_start_year) - ifelse(season == 'summer', 1, 0)
  
  # Adjust end year
  max_end_year <- relevant_data |>
    pull(.data$Year) |>
    max()
  end_year <-
    min(end_year, max_end_year) + ifelse(season == 'summer', 1, 0)
  
  # Extract relevant years
  relevant_data <- relevant_data |>
    filter(.data$Year >= start_year,
           .data$Year <= end_year)
  
  # Group months into relevant seasons
  if (season == 'summer') {
    relevant_data <- relevant_data |>
      mutate(
        Season = if_else(
          .data$Month > 10,
          .data$Year - start_year + 1,
          .data$Year - start_year
        ),
        Seasons_ago = end_year - start_year - .data$Season + 1
      )
  } else {
    relevant_data <- relevant_data |>
      mutate(
        Season = .data$Year - start_year + 1,
        Seasons_ago = end_year - start_year - .data$Season + 2
      )
  }
  
  # Remove irrelevant months of starting year
  if (season == 'summer') {
    relevant_data <- relevant_data |>
      filter(.data$Season > 0,
             .data$Seasons_ago > 0)
  }
  
  # Abort if dataset is empty
  stopifnot('There are no data to plot' = nrow(relevant_data) > 0)
  
  # Add rows for February 29th for non-leap-years to align February end date
  leap_years_in_data <-
    any(leap_year(unique(pull(
      relevant_data, .data$Year
    ))))
  if (leap_years_in_data) {
    leap_year_rows <- relevant_data |>
      filter(.data$Month == 2 & .data$Day == 28) |>
      mutate(Day = 29, Temperature = NA) |>
      filter(!leap_year(.data$Year))
    relevant_data <- relevant_data |>
      bind_rows(leap_year_rows) |>
      arrange(.data$Year, .data$Month, .data$Day)
  }
  
  # Determine day number within the season
  relevant_data <- relevant_data |>
    group_by(.data$Season) |>
    mutate(Day_number = row_number()) |>
    ungroup()
  
  # Determine extreme temperature categories
  decimal_places <-
    max(nchar(gsub(
      ".*\\.|^[^.]+$", "", as.character(pull(relevant_data, .data$Temperature))
    )), na.rm = TRUE)
  decimal_part <- 1 / (10 ^ decimal_places)
  if (season == 'summer') {
    threshold1 <- thresholds[1]
    threshold2 <- thresholds[2]
    threshold3 <- thresholds[3]
    threshold1_lower_num <- threshold1 + decimal_part
    threshold1_lower_chr <- as.character(threshold1_lower_num)
    threshold1_upper_num <- threshold2
    threshold1_upper_chr <-
      sprintf(paste0('%.', decimal_places, 'f'), threshold1_upper_num)
    threshold2_lower_num <- threshold2 + decimal_part
    threshold2_lower_chr <- as.character(threshold2_lower_num)
    threshold2_upper_num <- threshold3
    threshold2_upper_chr <-
      sprintf(paste0('%.', decimal_places, 'f'), threshold2_upper_num)
    threshold3_lower_num <- threshold2_upper_num
    threshold3_lower_chr <- threshold2_upper_chr
    threshold_inf <- Inf
  }
  if (season == 'winter') {
    threshold1 <- thresholds[3]
    threshold2 <- thresholds[2]
    threshold3 <- thresholds[1]
    threshold1_lower_num <- threshold2 + decimal_part
    threshold1_lower_chr <- as.character(threshold1_lower_num)
    threshold1_upper_num <- threshold1
    threshold1_upper_chr <-
      sprintf(paste0('%.', decimal_places, 'f'), threshold1_upper_num)
    threshold2_lower_num <- threshold3 + decimal_part
    threshold2_lower_chr <- as.character(threshold2_lower_num)
    threshold2_upper_num <- threshold2
    threshold2_upper_chr <-
      sprintf(paste0('%.', decimal_places, 'f'), threshold2_upper_num)
    threshold3_upper_num <- threshold2_lower_num
    threshold3_upper_chr <- threshold2_lower_chr
    threshold_inf <- -Inf
  }
  temp_cutoffs <-
    c(threshold1, threshold2, threshold3, threshold_inf)
  extreme_days <-
    filter(relevant_data, if (season == 'summer') {
      .data$Temperature > threshold1
    } else {
      .data$Temperature <= threshold1
    }) |>
    # Ensure all years are present for plotting on y-axis
    left_join(x = unique(select(relevant_data, c("Seasons_ago"))),
              y = _,
              by = "Seasons_ago") |>
    mutate(Temp_category = cut(.data$Temperature, temp_cutoffs))
  
  # Abort if dataset is empty
  stopifnot('There are no data to plot' = nrow(na.omit(extreme_days)) > 0)
  
  # Determine graph properties based on season
  measure_label <- unique(pull(relevant_data, .data$Type))
  temperature_symbol <- "\u00B0C"
  graph_edge_padding <- 4
  if (season == 'summer') {
    colours <- c("salmon", "red2", "black")
    year_breaks <- seq(1, end_year - start_year)
    year_labels <-
      str_c(
        as.character(seq(end_year - 1, start_year)),
        rep('-', end_year - start_year),
        str_sub(as.character(seq(
          end_year, start_year + 1
        )), -2, -1)
      )
    if (leap_years_in_data)
      month_breaks <- c(0, 30, 61, 92, 121, 152)
    else
      month_breaks <- c(0, 30, 61, 92, 120, 151)
    month_labels <-
      c("November", "December", "January", "February", "March")
    direction <- 'above'
    subtitle_threshold <- threshold2_upper_chr
    range1 <-
      paste0(
        threshold1_lower_chr,
        temperature_symbol,
        ' to ',
        threshold1_upper_chr,
        temperature_symbol
      )
    range2 <-
      paste0(
        threshold2_lower_chr,
        temperature_symbol,
        ' to ',
        threshold2_upper_chr,
        temperature_symbol
      )
    range3 <-
      paste0(str_to_title(direction),
             ' ',
             threshold3_lower_chr,
             temperature_symbol)
    legend_labels <- c(range1, range2, range3)
    legend_levels <-
      levels(cut((threshold1 - 1):(threshold3 + 1), temp_cutoffs))
    legend_limits <- legend_levels
  }
  if (season == 'winter') {
    colours <- c("black", "cornflowerblue", "lightblue")
    year_breaks <- seq(1, end_year - start_year + 1)
    year_labels <-
      rev(as.character(unique(pull(
        relevant_data, .data$Year
      ))))
    month_breaks <- c(0, 31, 61, 92, 123, 153)
    month_labels <- c("May", "June", "July", "August", "September")
    direction <- 'below'
    subtitle_threshold <- threshold2_lower_chr
    range1 <-
      paste0(
        threshold1_lower_chr,
        temperature_symbol,
        ' to ',
        threshold1_upper_chr,
        temperature_symbol
      )
    range2 <-
      paste0(
        threshold2_lower_chr,
        temperature_symbol,
        ' to ',
        threshold2_upper_chr,
        temperature_symbol
      )
    range3 <-
      paste0(str_to_title(direction),
             ' ',
             threshold3_upper_chr,
             temperature_symbol)
    legend_labels <- c(range3, range2, range1)
    legend_levels <-
      levels(cut((threshold3 - 1):(threshold1 + 1), temp_cutoffs))
    legend_limits <- legend_levels
  }
  
  # Count days of very extreme temperatures to display on right side of graph
  very_extreme_counts <- extreme_days |>
    group_by(.data$Seasons_ago) |>
    summarise(
      Very_extreme_days = sum(
        if (season == 'summer')
          .data$Temperature > threshold3
        else
          .data$Temperature <= threshold3
      )
    ) |>
    # Ensure no years with missing counts on graph
    left_join(x = unique(select(relevant_data, .data$Seasons_ago)),
              y = _,
              by = "Seasons_ago") |>
    replace_na(replace = list(Very_extreme_days = 0)) |>
    mutate(x_position = max(month_breaks) + graph_edge_padding)
  
  # Generate graph
  graph <-
    ggplot(
      extreme_days,
      aes(
        .data$Day_number,
        .data$Seasons_ago,
        fill = .data$Temp_category,
        na.rm = FALSE
      )
    ) +
    geom_tile(na.rm = TRUE) +
    scale_fill_manual(
      values = colours,
      name = paste(measure_label, "temperature:"),
      labels = legend_labels,
      limits = legend_limits
    ) +
    geom_vline(xintercept = month_breaks + 0.5) +
    scale_y_continuous(breaks = year_breaks,
                       labels = year_labels,
                       expand = c(0, 0)) +
    scale_x_continuous(
      # 'breaks' is defined as the midpoints of 'month_breaks' to centre-align 'month_labels'
      breaks = rollapply(
        month_breaks,
        width = 2,
        FUN = sum,
        by = 1
      ) / 2,
      labels = month_labels,
      expand = expansion(add = c(0, graph_edge_padding))
    ) +
    theme(
      panel.border = element_rect(color = 'black', fill = NA),
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.ticks = element_blank(),
      plot.title = element_text(hjust = 0.5),
      plot.title.position = "plot",
      plot.subtitle = element_text(hjust = 0.5),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "bottom"
    ) +
    labs(
      title = paste0(
        "Daily",
        " ",
        measure_label,
        " ",
        "Temperature",
        "\n",
        trimws(str_to_title(location))
      ),
      subtitle = paste0(
        "Numbers on the right are counts of days with temperatures",
        " ",
        direction,
        " ",
        subtitle_threshold,
        temperature_symbol
      )
    ) +
    geom_text(
      data = very_extreme_counts,
      aes(
        .data$x_position,
        .data$Seasons_ago,
        label = .data$Very_extreme_days
      ),
      inherit.aes = FALSE
    )
  
  # Return graph
  return(graph)
}
